// Code generated by hertz generator.

package main

import (
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	args := os.Args[1]
	h := server.Default(server.WithHostPorts(args))

	register(h)
	h.Spin()

}
