// Code generated by hertz generator.

package http

import (
	"context"

	http "gateway/biz/model/http"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// BizMethod1 .
// @router /BizService/BizMethod1 [POST]
func BizMethod1(ctx context.Context, c *app.RequestContext) {
	var err error
	var req http.BizRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http.BizResponse)

	c.JSON(consts.StatusOK, resp)
}

// BizMethod2 .
// @router /BizService/BizMethod2 [POST]
func BizMethod2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req http.BizRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http.BizResponse)

	c.JSON(consts.StatusOK, resp)
}

// BizMethod3 .
// @router /BizService/BizMethod3 [POST]
func BizMethod3(ctx context.Context, c *app.RequestContext) {
	var err error
	var req http.BizRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(http.BizResponse)

	c.JSON(consts.StatusOK, resp)
}
